/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.dnd.DropTarget;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import tool.Tool;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DropTargetDragEvent;
import java.awt.dnd.DropTargetDropEvent;
import java.awt.dnd.DropTargetEvent;
import java.awt.dnd.DropTargetListener;
import java.io.File;
import java.util.List;
import test.TestFrame;

/**
 *
 * @author Administrator
 */
public class DatDispose_GUI extends javax.swing.JFrame {

    /**
     * Creates new form DatDispose_GUI
     */
    DatDispose_GUI miangui = this;

    public DatDispose_GUI() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("文件抽取工具-[作者：陈立]<QQ:185817196>");

        //添加拖拽效果
        DndTargetListener dnd=new DndTargetListener();
        jTextField1.setDropTarget(new DropTarget(this, DnDConstants.ACTION_REFERENCE,
                dnd, true));
    }

    /**
     *
     * @author Administrator
     */
    public class DndTargetListener implements DropTargetListener {

        @Override
        public void dragEnter(DropTargetDragEvent arg0) {
            System.out.println("dragEnter");
        }

        @Override
        public void dragExit(DropTargetEvent arg0) {
            System.out.println("dragExit");
        }

        @Override
        public void dragOver(DropTargetDragEvent arg0) {
            //    System.out.println("dragOver");
        }

        @Override
        public void drop(DropTargetDropEvent arg0) {
            System.out.println("drop");
            arg0.acceptDrop(DnDConstants.ACTION_REFERENCE);
            if (arg0.isDataFlavorSupported(DataFlavor.javaFileListFlavor)) {
                try {
                    Transferable tf = arg0.getTransferable();
                    List<File> list = (List<File>) tf
                            .getTransferData(DataFlavor.javaFileListFlavor);
                    for (File f : list) {
                        if (f.exists() && f.isFile()) {//如果是文件
                             jTextField1.setText(f.getParent());
                             return;
                        } else if (f.exists() && f.isDirectory()) {//如果是文件夹
                            // 这里不对拖拽文件夹做操作
                             jTextField1.setText(f.getAbsolutePath());
                             return;
                        }
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }

        @Override
        public void dropActionChanged(DropTargetDragEvent arg0) {
            System.out.println("dropActionChanged");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("同类文件目标转移");

        jLabel2.setText("目录选择：");

        jTextField1.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("文件后缀名：");

        jTextField2.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jTextField2.setText("dat");

        jButton1.setText("浏览");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("保存目录：");

        jTextField3.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N

        jButton2.setText("浏览");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jButton3.setText("快速保存到桌面");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jButton4.setText("移动到保存目录");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTxt.setColumns(20);
        jTxt.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTxt.setRows(5);
        jTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTxtMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTxt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(73, 73, 73)
                .addComponent(jButton3)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        jTextField1.setText(Tool.Tool().getDirOrFile(this, "d"));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    //保存目录
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField3.setText(Tool.Tool().getDirOrFile(this, "d"));
    }//GEN-LAST:event_jButton2ActionPerformed
//开始移动
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String dirPath = jTextField1.getText();//获得需转移的目录
        String suffix = jTextField2.getText();//需转移的文件后缀名
        String savePath = jTextField3.getText() + "\\" + suffix + "-文件" + Tool.Tool().getTime();//保存目录 
        if (jTextField1.getText() == null || jTextField2.getText() == null || jTextField3.getText() == null
                || jTextField1.getText().equals("") || jTextField2.getText().equals("") || jTextField3.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "信息填写不完整!");
            return;
        }
        MoveFile mf = new MoveFile(dirPath, suffix, savePath);
        mf.start();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String dirPath = jTextField1.getText();//获得需转移的目录
        String suffix = jTextField2.getText();//需转移的文件后缀名
        String savePath = Tool.Tool().deskPath + "\\" + suffix + "-文件" + Tool.Tool().getTime();
        System.out.println(savePath);
        if (jTextField1.getText() == null || jTextField2.getText() == null
                || jTextField1.getText().equals("") || jTextField2.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "信息填写不完整!");
        }
        MoveFile mf = new MoveFile(dirPath, suffix, savePath);
        mf.start();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTxtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtMouseReleased
        // TODO add your handling code here:
        //创建右键菜单
        JPopupMenu popMenu = new JPopupMenu();
        if (evt.isPopupTrigger()) { //判断是否为右键单击，以便实现右键弹出菜单         
            //声明
            JMenuItem MenuRootNode = new JMenuItem("查找");
            // 添加
            popMenu.add(MenuRootNode);
            //显示右键菜单
            popMenu.show(evt.getComponent(), evt.getX(), evt.getY());
            //右键菜单事件
            //查找
            MenuRootNode.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new findString(miangui).setVisible(true);
                        }
                    });
                }
            });

        }
    }//GEN-LAST:event_jTxtMouseReleased

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseReleased

    class MoveFile extends Thread {

        String dirPath;
        String suffix;
        String savePath;

        public MoveFile(String dirPath, String suffix, String savePath) {
            this.dirPath = dirPath;
            this.suffix = suffix;
            this.savePath = savePath;
        }

        public void run() {
            ArrayList<File> list = new ArrayList<File>();
            String fileName;
            jTxt.setText("");
            jTxt.append("开始执行：" + "\r\n");
            list = Tool.Tool().getFileList(new File(dirPath), list, suffix, jTxt);//获得类型文件list
            for (int i = 0; i < list.size(); i++) {
                try {
                    fileName = Tool.Tool().writeFileTo(list.get(i).getPath(), savePath);
                    jTxt.append(fileName + "\r\n" + "原目录：" + list.get(i).getPath() + "\r\n\r\n");
                    jTxt.setCaretPosition(jTxt.getText().length());
                } catch (Exception ex) {
                    jTxt.append("出错！程序终止···" + ex.getMessage() + "\r\n");
                    ex.printStackTrace();
                }
            }
            JOptionPane.showMessageDialog(miangui, "成功!目录：" + savePath);
        }
    }

    public void startProject() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatDispose_GUI().setVisible(true);
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } catch (InstantiationException ex) {
            ex.printStackTrace();
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatDispose_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatDispose_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatDispose_GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    public javax.swing.JTextArea jTxt;
    // End of variables declaration//GEN-END:variables
}
