/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import tool.Tool;

/**
 *
 * @author Administrator
 */
public class PartFile_GUI extends javax.swing.JFrame {

    /**
     * Creates new form PartFile_GUI
     */
    PartFile_GUI miangui = this;
    int FGjinDu;

    public PartFile_GUI() {

        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("文件分割还原工具-[作者：陈立]<QQ:185817196>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFenGe = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSave = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSize = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jMIniSize = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jHuanYuan = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("文件分割还原工具");

        jLabel2.setText("需分割的文件：");

        jButton1.setText("浏览");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("保存路径：");

        jButton2.setText("浏览");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("文件大小：");

        jSize.setEditable(false);

        jLabel5.setText("最小分割单元：");

        jLabel6.setText("M");

        jLabel7.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("清输入数字");

        jLabel8.setText("选择还原文件：");

        jButton3.setText("浏览");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        jButton4.setText("开始分割");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        jButton5.setText("开始还原");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(380, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel4))
                                .addComponent(jLabel3))
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSize, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jMIniSize, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jFenGe)
                            .addComponent(jSave)
                            .addComponent(jHuanYuan))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFenGe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jMIniSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jHuanYuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //JFileChooser JFC=new JFileChooser();
        JFileChooser chooser = new JFileChooser(Tool.chooseStartPath);
//        FileNameExtensionFilter filter = new FileNameExtensionFilter(
//            "JPG & GIF Images", "jpg", "gif");
//        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(this);
        String fileSize = null;//文件大小
        if (returnVal == JFileChooser.APPROVE_OPTION) {

            Tool.filePath = chooser.getSelectedFile().getPath();//获得文件路径
            jFenGe.setText(Tool.filePath);
            fileSize = Tool.Tool().formatFileSize(chooser.getSelectedFile().length());
            jSize.setText(fileSize);
        }

    }//GEN-LAST:event_jButton1ActionPerformed
//文件保存位置获取
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser(Tool.chooseStartPath);
        chooser.setDialogTitle("目录选择器");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            Tool.chooseStartPath = file.getPath();
            jSave.setText(Tool.chooseStartPath);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (jFenGe.getText() == null || jSave.getText() == null || jMIniSize.getText() == null
                || jFenGe.getText().equals("") || jMIniSize.getText().equals("") || jSave.getText().equals("")) {
            JOptionPane.showMessageDialog(miangui, "信息填写不完整!");
            return;
        }
        String partFile = jFenGe.getText();//切割文件路径
        String saveFile = jSave.getText();//保存目录路径
        long partSize = Long.parseLong(jMIniSize.getText()) * 1024 * 1024;//分割的最小单元
        FenGe fg = new FenGe(partFile, saveFile, partSize);
        fg.start();
    }//GEN-LAST:event_jButton4ActionPerformed
//还原文件选择
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser(Tool.chooseStartPath);
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "jy1091part", "jy1091part");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String filePath = chooser.getSelectedFile().getPath();
            if (!filePath.endsWith("jy1091part")) {
                filePath = null;
                return;
            }
            jHuanYuan.setText(filePath);//获得文件路径

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    class HuanYuan extends Thread {

        String filePath = null;
        InputStream is = null;
        OutputStream os = null;

        public HuanYuan(String filePath) {
            this.filePath = filePath;
        }

        public void run() {
            File file = null;
            String fileName = filePath.substring(0, filePath.lastIndexOf("-"));//获取真实的文件名
            if (new File(fileName).exists()) {
                System.out.println("文件存在！不进行还原");
                return;
            }
            try {
                os = new FileOutputStream(fileName, true);

                System.out.println(fileName);
                int i = 1;
                byte[] data = new byte[1024 * 1024];
                while (true) {
                    file = new File(fileName + "-" + i + ".jy1091part");
                    if (file.exists()) {
                        System.out.println("文件存在");
                    } else {
                        System.out.println(file.getPath() + "文件不存在");
                    }
                    if (!file.exists()) {//如果文件不存在
                        return;
                    }
                    is = new FileInputStream(file);
                    long yuShu = file.length() % (1024 * 1024);//余数
                    long duoS = file.length() / 1024 / 1024;
                    if (yuShu != 0) {
                        duoS++;
                    }
                    int count = 0;
                    while (is.read(data, 0, data.length) != -1) {
                        count++;

                        os.write(data, 0, data.length);
                        if (yuShu != 0 && duoS == count - 1) {
                            data = new byte[Integer.parseInt(yuShu + "")];
                        }
                    }
                    count = 0;
                    is.close();

                    i++;
                }

            } catch (Exception ex) {
                ex.printStackTrace();
            } finally {
                try {
                    JOptionPane.showMessageDialog(miangui, "还原成功!");
                    if (is != null) {
                        is.close();
                    }
                    if (os != null) {
                        os.close();
                    }
                } catch (IOException ex) {
                    Logger.getLogger(PartFile_GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (jHuanYuan.getText() == null
                || jHuanYuan.getText().equals("")) {
            JOptionPane.showMessageDialog(miangui, "信息填写不完整!");
            return;
        }
        String filePath = jHuanYuan.getText();//取得还原的文件
        HuanYuan hy = new HuanYuan(filePath);
        hy.start();

    }//GEN-LAST:event_jButton5ActionPerformed

    class FenGe extends Thread {

        String partFile = null;//需分割的文件路径
        String saveFile = null;//保存的路径
        long partSize;//分割文件的最小单元
        InputStream is = null;
        OutputStream os = null;

        public FenGe(String partFile, String saveFile, long partSize) {
            this.partFile = partFile;
            this.saveFile = saveFile;
            this.partSize = partSize;
        }

        public void run() {
            try {
                is = new FileInputStream(this.partFile);
                long n = 0;//记录总共读取的字节数
                int i = 1;//计数器
                byte[] data = new byte[1024 * 1024];
                long fileSize = new File(this.partFile).length();
                long count = fileSize / partSize;//分成多少部分
                int yuShu = Integer.parseInt(fileSize % partSize + "");
                System.out.println("文件大小：" + fileSize + "余数：" + yuShu);
                if (yuShu != 0) {
                    count++;
                }
                os = new FileOutputStream(this.saveFile + "\\" + (new File(this.partFile).getName() + "-" + i + ".jy1091part"));
                while (n < fileSize) {
                    if (n >= partSize && n % partSize == 0) {
                        i++;//part加一
                        System.out.println(" i:" + i + "  count:" + count);
                        os.close();
                        os = new FileOutputStream(this.saveFile + "\\" + (new File(this.partFile).getName() + "-" + i + ".jy1091part"));
                    }
                    if (i == count) {
                        System.out.println("执行到：" + count + " i:" + i);
                        data = new byte[yuShu];
                    }

                    n = n + is.read(data, 0, data.length);
                    System.out.println("读取的字节数：" + Tool.Tool().formatFileSize(n));
                    os.write(data, 0, data.length);
                }
                is.close();//关闭
                os.close();
                JOptionPane.showMessageDialog(miangui, "分割成功!");
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }

    
        public void startProject() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PartFile_GUI().setVisible(true);
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartFile_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartFile_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartFile_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartFile_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        PartFile_GUI p=new PartFile_GUI();
        p.startProject();
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PartFile_GUI().setVisible(true);
//            }
//        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JTextField jFenGe;
    private javax.swing.JTextField jHuanYuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jMIniSize;
    private javax.swing.JTextField jSave;
    private javax.swing.JTextField jSize;
    // End of variables declaration//GEN-END:variables
}
